#附魔限制插件配置文件
#配置文件版本
version: '1.0'
#最大允许的附魔等级
#附魔等级的概念：
#在可视的附魔等级内，这个数字代表了我们看到的罗马数字
#比如锋利III的附魔等级为3
#MC允许的安全范围内，这个值不应超过127
#插件允许的范围内，这个值不应超过65535
#从代码角度说，这个值不能超过2147483647，但当设置值超出65535时是无意义的
maxLevel: 20
#是否对使用超过附魔物品的人进行ban的惩罚
isBanned: false
#当扫描到时提示什么
message: '&4你使用了超过规定附魔等级的物品！'
#是否删除此物品
isDelItem: true
#是否清除此物品的附魔，不要和删除同开
isClearEnchantment: false
#细节性功能
more:
#针对于不同的附魔，拥有不同的附魔限制
  enchantment:
#是否启用该功能
    enable: false
#单独为不同的附魔设置不同的附魔等级限制，设置为0表示使用上面的maxLevel值
#以下括号里标注的是附魔的ID
#盔甲类附魔，可以统一使用ID=65表示
#保护 (0)
    PROTECTION_ENVIRONMENTAL: 0
#火焰保护 (1)
    PROTECTION_FIRE: 0
#摔落保护 (2)
    PROTECTION_FALL: 0
#爆炸保护 (3)
    PROTECTION_EXPLOSIONS: 0
#弹射物保护 (4)
    PROTECTION_PROJECTILE: 0
#水下呼吸 (5)
    OXYGEN: 0
#水下速掘 (6)
    WATER_WORKER: 0
#荆棘 (7)
    THORNS: 0
#深海探索者 (8)
#这项只在1.8版本14w25a后可用
    DEPTH_STRIDER: 0
#冰霜行者 (9)
#这项只在1.9版本15w42a后可用
    FROST_WALKER: 0
#武器类附魔，可以统一使用ID=66表示
#锋利 (16)
    DAMAGE_ALL: 0
#亡灵杀手 (17)
    DAMAGE_UNDEAD: 0
#节肢杀手 (18)
    DAMAGE_ARTHROPODS: 0
#击退 (19)
    KNOCKBACK: 0
#火焰附加 (20)
    FIRE_ASPECT: 0
#抢夺 (21)
    LOOT_BONUS_MOBS: 0
#工具类附魔，可以统一使用ID=67表示
#效率 (32)
    DIG_SPEED: 0
#精准采集 (33)
    SILK_TOUCH: 0
#弓类附魔，可以统一使用ID=68表示
#弓_耐久 (34)
    DURABILITY: 0
#弓_时运 (35)
    LOOT_BONUS_BLOCKS: 0
#弓_力量 (48)
    ARROW_DAMAGE: 0
#弓_击退 (49)
    ARROW_KNOCKBACK: 0
#弓_火焰附加 (50)
    ARROW_FIRE: 0
#弓_无限 (51)
    ARROW_INFINITE: 0
#钓鱼竿类附魔，可以统一使用ID=69表示
#海之眷顾 (61)
    LUCK: 0
#诱饵 (62)
    LURE: 0
#下面这个我实在是没法分成一类，反正它也是单独一个
#经验修补 (63)
#这项只在1.9版本15w42a后可用
    MENDING: 0
#禁止向某个物品附魔功能
  banItem:
#是否启用该功能
    enable: false
#禁止附魔的物品ID添加到下面的列表里
#这里可以使用上面分类的附魔ID，即65-69
#格式采用 物品ID:附魔ID 的形式
#表示不允许该物品添加该ID对应的附魔，可以多个:
#不加:默认禁止全部的附魔
#如果认为禁附魔很麻烦 可以选择以下形式
#格式采用 物品ID;附魔ID 的形式
#表示只允许添加该ID的附魔，可以多个;
#注意：这项会主动跳过不存在的ID
#但不包括不能识别的ID
    list:
      - '340'       #表示禁止书进行任何附魔
      - '310;65'    #表示只允许钻石头盔附魔保护类的附魔
      - '311:66'    #表示不允许钻石胸甲附魔武器类的附魔